# Generated by Django 5.1.2 on 2025-01-02 13:30

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aashfApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HActiviti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=255)),
                ('a_details', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='hospital_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('role', models.CharField(choices=[('Patient', 'রোগী'), ('Doctor', 'ডাক্তার')], default='Patient', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='see_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NikahRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('groom_name', models.CharField(max_length=255, verbose_name='বরের পুরো নাম (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('groom_present_address', models.TextField(verbose_name='বরের বর্তমান ঠিকানা (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('groom_permanent_address', models.TextField(verbose_name='বরের স্থায়ী ঠিকানা (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('groom_occupation', models.TextField(verbose_name='বরের পেশা (পদবীসহ প্রতিষ্ঠানের নাম, ঠিকানা)')),
                ('groom_education', models.CharField(max_length=255, verbose_name='বরের সর্বোচ্চ শিক্ষাগত যোগ্যতা')),
                ('groom_nid', models.CharField(max_length=255, verbose_name='বরের জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন নম্বর')),
                ('groom_mobile', models.CharField(max_length=255, verbose_name='বরের মোবাইল নম্বর')),
                ('groom_alternate_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='বরের বিকল্প মোবাইল নম্বর (যদি থাকে)')),
                ('groom_father', models.CharField(max_length=255, verbose_name='বরের পিতার নাম (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('groom_father_mobile', models.CharField(max_length=255, verbose_name='বরের পিতা/মাতার মোবাইল নম্বর')),
                ('bride_name', models.CharField(max_length=255, verbose_name='কনের পুরো নাম (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('bride_present_address', models.TextField(verbose_name='কনের বর্তমান ঠিকানা (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('bride_permanent_address', models.TextField(verbose_name='কনের স্থায়ী ঠিকানা (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('bride_occupation', models.TextField(verbose_name='কনের পেশা (চাকুরিরত হলে, প্রতিষ্ঠানের নাম, ঠিকানা)')),
                ('bride_education', models.CharField(max_length=255, verbose_name='কনের সর্বোচ্চ শিক্ষাগত যোগ্যতা')),
                ('bride_nid', models.CharField(max_length=255, verbose_name='কনের জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন নম্বর')),
                ('bride_mobile', models.CharField(max_length=255, verbose_name='কনের মোবাইল নম্বর')),
                ('bride_alternate_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='কনের বিকল্প মোবাইল নম্বর (যদি থাকে)')),
                ('bride_father', models.CharField(max_length=255, verbose_name='কনের পিতা/অভিভাবকের নাম (জাতীয় পরিচয়পত্র / জন্ম নিবন্ধন অনুযায়ী) লিখুন')),
                ('bride_father_mobile', models.CharField(max_length=255, verbose_name='কনের পিতা/মাতার মোবাইল নম্বর')),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='আবেদনকারীর নাম (বর/কনের পক্ষে অন্য কেউ আবেদনকারী হলে)')),
                ('applicant_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='আবেদনকারীর মোবাইল নম্বর')),
                ('applicant_groom', models.CharField(blank=True, choices=[('মামা/চাচা/খালু', 'মামা/চাচা/খালু'), ('মামী/চাচী/খালা', 'মামী/চাচী/খালা'), ('ফুফু/ফুফা', 'ফুফু/ফুফা'), ('অন্যান্য', 'অন্যান্য')], max_length=255, null=True, verbose_name='আবেদনকারীর সাথে বরের সম্পর্ক কী? বর নিজে আবেদনকারী হলে এ প্রশ্ন এড়িয়ে চলুন')),
                ('applicant_bride', models.CharField(blank=True, choices=[('মামা/চাচা/খালু', 'মামা/চাচা/খালু'), ('মামী/চাচী/খালা', 'মামী/চাচী/খালা'), ('ফুফু/ফুফা', 'ফুফু/ফুফা'), ('অন্যান্য', 'অন্যান্য')], max_length=255, null=True, verbose_name='আবেদনকারীর সাথে কনের সম্পর্ক কী? কনে নিজে আবেদনকারী হলে এ প্রশ্ন এড়িয়ে চলুন')),
                ('groom_image', models.ImageField(upload_to='event_groom', verbose_name='বরের ছবি (সদ্য তোলা পাসপোর্ট সাইজের ছবি, কোন সেলফি গ্রহণযোগ্য হবে না)')),
                ('bride_image', models.ImageField(upload_to='event_bride', verbose_name='কনের ছবি (সদ্য তোলা পাসপোর্ট সাইজের ছবি, কোন সেলফি গ্রহণযোগ্য হবে না)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nikah_reg_event', to='aashfApp.event')),
            ],
        ),
    ]
