# Generated by Django 5.1.2 on 2025-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
    ]
