# Generated by Django 5.1.2 on 2025-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahospital', '0004_remove_nikahregistration_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='NikahRegistration',
        ),
    ]
