# Generated by Django 5.1.2 on 2025-01-02 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahospital', '0006_nikahregistration_delete_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='see_user', to='ahospital.myuser'),
        ),
    ]
