# Generated by Django 5.1.2 on 2025-01-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aashfApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Vol_Registration',
        ),
    ]
