from django.urls import path, include
from .views import *
urlpatterns = [
    path('map/', map_view, name='map'),
    path('events/', eventview, name='event'),
    path('projects/', projectview, name='project'),
    path('videos/', videoview, name='video'),
    path('activities/', activityview, name='activity'),
    path('campaigns/', campaignview, name='campaign'),
    path('rohingyas/', rohingyaview, name='rohingya'),
    path('legals/', legalview, name='legal'),
    path('blogs/', blogview, name='blog'),
    path('events/register/<int:id>/', event_register, name='event_register'),
    path('events/details/<int:id>/', event_detail, name='event_detail'),
    path('projects/details/<int:id>/', project_detail, name='project_detail'),
    path('activities/details/<int:id>/', activity_detail, name='activity_detail'),
    path('campaigns/details/<int:id>/', campaign_detail, name='campaign_detail'),
    path('rohingyas/details/<int:id>/', rohingya_detail, name='rohingya_detail'),
    path('legals/details/<int:id>/', legal_detail, name='legal_detail'),
    path('blogs/details/<int:id>/', blog_detail, name='blog_detail'),
    path('gallery/', gallery, name='gallery'),
    path('gb/', gbview, name='gb'),
    path('advisors/', apview, name='ap'),
    path('volunteers/', volunteerview, name='volunteer'),
    path('awards/', awardview, name='award'),
    path('mission/', missionview, name='mission'),
    path('contact/', contactview, name='contact'),
    path('search/', search, name='search'),
    path('<str:country>/', homeview, name='home'),
    path('', redirect_to_bangladesh),
]